### ISSUE TITLE
Problem with  selecting multiple license types for same download

### ISSUE THREAD

**Issue by biolars** [cypamigon/inat_downloader#1]
Thanks a lot for this useful resource!
I am having problems though selecting multiple licenses types for the same download.
I cannot seem to get it working with a shoirt list of licenses seoerated by ",".
Cheers

**Comment by cypamigon** [comment]
Hi biolars, 

Can you check that you are not adding any spaces after "," characters ? The syntax must follow this structure : 

```
python inat_downloader.py -l cc-by,cc-by-nc,cc-by-sa,cc-by-nd,cc-by-nc-sa
```

Can you provide the typed command and the output logs ?

**Comment by biolars** [comment]
I just tested it again and it works as expected! Maybe I did forget to leave out the spaces!
Thanks!
